# Generated by Django 2.2 on 2019-10-04 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDocumento', models.CharField(max_length=128, verbose_name='Número')),
                ('titulo', models.CharField(max_length=128, verbose_name='Título do Processo')),
                ('data', models.DateField(verbose_name='Data')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('data_de_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('telefone_celular', models.CharField(blank=True, help_text='Número de Telefone celular no formato (99) 99999-9999', max_length=15, null=True, verbose_name='Telefone Celular')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroProcesso', models.CharField(max_length=128, verbose_name='Número')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo.Departamento')),
                ('interessados', models.ManyToManyField(related_name='Interessados', to='app_processo.Pessoa')),
                ('investigados', models.ManyToManyField(related_name='Investigados', to='app_processo.Pessoa')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_processo.Pessoa')),
                ('matricula', models.CharField(max_length=15)),
            ],
            bases=('app_processo.pessoa',),
        ),
        migrations.CreateModel(
            name='PedidoDePrazo',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_processo.Documento')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('data_anterior', models.DateField(verbose_name='Data Anterior')),
                ('novo_prazo', models.DateField(verbose_name='Novo Prazo')),
            ],
            options={
                'verbose_name': 'Pedido de Prazo',
                'verbose_name_plural': 'Pedidos de Prazo',
            },
            bases=('app_processo.documento',),
        ),
        migrations.CreateModel(
            name='PortariaDeInstauracao',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_processo.Documento')),
                ('iniciou', models.BooleanField(verbose_name='Processo iniciado?')),
            ],
            options={
                'verbose_name': 'Portaria de Instauração',
                'verbose_name_plural': 'Portarias de Instauração',
            },
            bases=('app_processo.documento',),
        ),
        migrations.CreateModel(
            name='Tramitacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimentacao', models.DateField(verbose_name='Data Movimentação')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Destino', to='app_processo.Departamento')),
                ('origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Origem', to='app_processo.Departamento')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo.Processo')),
            ],
            options={
                'verbose_name': 'Tramitação',
                'verbose_name_plural': 'Tramitações',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo.Processo'),
        ),
        migrations.AddField(
            model_name='documento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processo',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo.Funcionario'),
        ),
        migrations.CreateModel(
            name='EnvioDeProcesso',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_processo.Documento')),
                ('data_anterior', models.DateField(verbose_name='Data Anterior')),
                ('data_mudanca', models.DateField(verbose_name='Data Mudança')),
                ('departamento_tramite', models.ManyToManyField(related_name='Departamento', to='app_processo.Departamento')),
            ],
            options={
                'verbose_name': 'Envio de Processo',
                'verbose_name_plural': 'Envio de Processos',
            },
            bases=('app_processo.documento',),
        ),
    ]
