# Generated by Django 2.2 on 2019-10-04 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_processo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo.Funcionario'),
        ),
    ]
